### ISSUE TITLE
Karma

### ISSUE THREAD

**Issue by timduddy** [JayChase/angular2-useful-swiper#32]
Everything is working exactly how it should until I try to run tests then I get this error:

`ReferenceError: Swiper is not defined
    at SwiperComponent.webpackJsonp.../../../../angular2-useful-swiper/lib/swiper.component.js.SwiperComponent.setup (http://localhost:9876/_karma_webpack_/vendor.bundle.js:674:35)
    at SwiperComponent.webpackJsonp.../../../../angular2-useful-swiper/lib/swiper.component.js.SwiperComponent.ngAfterViewInit (http://localhost:9876/_karma_webpack_/vendor.bundle.js:665:18)
    at callProviderLifecycles (http://localhost:9876/_karma_webpack_/vendor.bundle.js:77068:18)
    at callElementProvidersLifecycles (http://localhost:9876/_karma_webpack_/vendor.bundle.js:77043:13)
    at callLifecycleHooksChildrenFirst (http://localhost:9876/_karma_webpack_/vendor.bundle.js:77027:17)
    at checkAndUpdateView (http://localhost:9876/_karma_webpack_/vendor.bundle.js:78132:5)
    at callViewAction (http://localhost:9876/_karma_webpack_/vendor.bundle.js:78489:21)
    at execComponentViewsAction (http://localhost:9876/_karma_webpack_/vendor.bundle.js:78421:13)
    at checkAndUpdateView (http://localhost:9876/_karma_webpack_/vendor.bundle.js:78130:5)
    at callWithDebugContext (http://localhost:9876/_karma_webpack_/vendor.bundle.js:79344:42)`

I am importing the module into the test.

**Comment by timduddy** [comment]
Never mind, this was my problem I figured it out.
